/**
 * Build-time script: scans public/signs/ (and subfolders) for .svg and .png
 * and generates src/signCatalog.generated.js.
 *
 * Run: npm run generate:signs (or node scripts/generateSignCatalog.js from project root)
 *
 * Folder layout:
 *   public/signs/C-001.svg              → id: "C-001", category: "general"
 *   public/signs/construction/C-018.svg  → id: "construction/C-018", category: "construction"
 *
 * Stable IDs = path relative to signs folder, no extension (forward slashes).
 * Label = filename without extension (override in signCatalog.overrides.js if needed).
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = path.resolve(__dirname, "..");
const SIGNS_DIR = path.join(PROJECT_ROOT, "public", "signs");
const OUT_FILE = path.join(PROJECT_ROOT, "src", "signCatalog.generated.js");

const DEFAULT_WIDTH = 64;
const DEFAULT_HEIGHT = 64;

function collectSignFiles(dir, baseRelative = "") {
  const entries = [];
  if (!fs.existsSync(dir)) return entries;
  const items = fs.readdirSync(dir, { withFileTypes: true });
  for (const item of items) {
    const full = path.join(dir, item.name);
    const rel = baseRelative ? `${baseRelative}/${item.name}` : item.name;
    if (item.isDirectory()) {
      entries.push(...collectSignFiles(full, rel));
    } else if (item.isFile()) {
      const ext = path.extname(item.name).toLowerCase();
      if (ext === ".svg" || ext === ".png") {
        entries.push({ fullPath: full, relativePath: rel });
      }
    }
  }
  return entries;
}

function relativePathToId(relativePath) {
  return relativePath.replace(/\.[^.]+$/, "").replace(/\\/g, "/");
}

function relativePathToCategory(relativePath) {
  const parts = relativePath.replace(/\\/g, "/").split("/");
  return parts.length > 1 ? parts[0] : "general";
}

function basenameToLabel(basename) {
  return basename.replace(/\.[^.]+$/, "");
}

function generateCatalog() {
  const files = collectSignFiles(SIGNS_DIR);
  const entries = files.map(({ relativePath }) => {
    const id = relativePathToId(relativePath);
    const category = relativePathToCategory(relativePath);
    const basename = path.basename(relativePath, path.extname(relativePath));
    const label = basenameToLabel(path.basename(relativePath));
    const src = "/signs/" + relativePath.replace(/\\/g, "/");
    return {
      id,
      label,
      category,
      src,
      defaultWidth: DEFAULT_WIDTH,
      defaultHeight: DEFAULT_HEIGHT,
      supportsTripod: true,
      supportsWindmaster: true,
      supportsRotation: true,
    };
  });
  // Sort by category then id for stable output
  entries.sort((a, b) => {
    const c = (a.category || "").localeCompare(b.category || "");
    return c !== 0 ? c : (a.id || "").localeCompare(b.id || "");
  });
  return entries;
}

function escapeStr(s) {
  return JSON.stringify(s);
}

function writeGeneratedFile(entries) {
  const lines = [
    "// Auto-generated by scripts/generateSignCatalog.js — do not edit by hand.",
    "// Add SVG/PNG files under public/signs/ or public/signs/<category>/ and run: npm run generate:signs",
    "",
    "export const SIGN_CATALOG_GENERATED = [",
    ...entries.map(
      (e) =>
        `  { id: ${escapeStr(e.id)}, label: ${escapeStr(e.label)}, category: ${escapeStr(e.category)}, src: ${escapeStr(e.src)}, defaultWidth: ${e.defaultWidth}, defaultHeight: ${e.defaultHeight}, supportsTripod: ${e.supportsTripod}, supportsWindmaster: ${e.supportsWindmaster}, supportsRotation: ${e.supportsRotation} },`
    ),
    "];",
    "",
    `export const GENERATED_AT = ${escapeStr(new Date().toISOString())};`,
  ];
  fs.writeFileSync(OUT_FILE, lines.join("\n"), "utf8");
}

const entries = generateCatalog();
writeGeneratedFile(entries);
console.log(`signCatalog: wrote ${entries.length} sign(s) to ${path.relative(PROJECT_ROOT, OUT_FILE)}`);
